services:
  ac_web:
    build: .
    container_name: ac_web
    env_file: .env
    ports:
      - "${PORT:-5000}:5000"
      - "9600:9600/udp"
      - "9600:9600/tcp"
      - "8081:8081"
    volumes:
      - "${SERVER_PATH}:/ac_server:rw"
