[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
loglevel=info

[program:servicepy]
command=python /app/app.py
autostart=true
autorestart=true
stdout_logfile=/var/log/servicepy.log
stderr_logfile=/var/log/servicepy.err

[program:acserver]
command=/ac_server/acserver
autostart=true
autorestart=true
stdout_logfile=/var/log/acserver.log
stderr_logfile=/var/log/acserver.err